content = (
    '"use client";\n\n'
    'import Link from "next/link";\n'
    'import { usePathname } from "next/navigation";\n'
    'import { Home, Package, Truck, Globe, User } from "lucide-react";\n\n'
    'const TABS = [\n'
    '  { href: "/home",           label: "\ud648",       icon: Home },\n'
    '  { href: "/pickup",         label: "\uc218\uac70\uc2e0\uccad", icon: Truck },\n'
    '  { href: "/warehouse",      label: "\ub9c8\uc774\ucc3d\uace0", icon: Package },\n'
    '  { href: "/shipping-request", label: "\ucd9c\uace0\uc2e0\uccad", icon: Globe },\n'
    '  { href: "/mypage",         label: "\ub9c8\uc774\ud398\uc774\uc9c0",icon: User },\n'
    '];\n\n'
    'export default function BottomTabBar() {\n'
    '  const pathname = usePathname();\n\n'
    '  return (\n'
    '    <nav\n'
    '      className="fixed bottom-0 left-0 right-0 bg-white border-t border-gray-100 z-50"\n'
    '      style={{ paddingBottom: "var(--sab, 0px)" }}\n'
    '    >\n'
    '      <div className="max-w-[600px] mx-auto flex">\n'
    '        {TABS.map(({ href, label, icon: Icon }) => {\n'
    '          const active = pathname.startsWith(href);\n'
    '          return (\n'
    '            <Link\n'
    '              key={href}\n'
    '              href={href}\n'
    '              className="flex-1 flex flex-col items-center justify-center py-2 gap-0.5"\n'
    '            >\n'
    '              <Icon\n'
    '                size={22}\n'
    '                className={active ? "text-blue-600" : "text-gray-400"}\n'
    '                strokeWidth={active ? 2.5 : 1.8}\n'
    '              />\n'
    '              <span\n'
    '                className={`text-[10px] font-medium ${\n'
    '                  active ? "text-blue-600" : "text-gray-400"\n'
    '                }`}\n'
    '              >\n'
    '                {label}\n'
    '              </span>\n'
    '            </Link>\n'
    '          );\n'
    '        })}\n'
    '      </div>\n'
    '    </nav>\n'
    '  );\n'
    '}\n'
)

with open("apps/web/components/ui/BottomTabBar.tsx", "w", encoding="utf-8", newline="\n") as f:
    f.write(content)

print("done")
